services:
  db:
    image: postgres:16
    container_name: postgres_orcamento
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: orcamento
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nest_orcamento
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://dev:dev@db:5432/orcamento
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    working_dir: /app

volumes:
  pgdata:
