services:
  db:
    image: mysql:8.0
    container_name: mysql_orcamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orcamento
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      TZ: America/Sao_Paulo
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  backend:
    build: .
    container_name: nest_orcamento
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      TZ: America/Sao_Paulo
      DATABASE_URL: mysql://dev:dev@db:3306/orcamento
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    working_dir: /app

volumes:
  mysqldata:
